from datetime import datetime

from sqlalchemy import (
    Boolean, Column, DateTime, ForeignKey,
    Integer, JSON, String, Text,
)
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


class Classroom(Base):
    """One classroom = one parent group."""
    __tablename__ = "classrooms"

    id                  = Column(Integer, primary_key=True, index=True)
    name                = Column(String, nullable=False)
    school_url          = Column(String, default="https://lasalle.gsepty.com")
    whatsapp_group_id   = Column(String, nullable=True)   # WhatsApp group JID e.g. "1234567890-1234567890@g.us"
    is_active           = Column(Boolean, default=True)
    created_at          = Column(DateTime, default=datetime.utcnow)

    parents  = relationship("Parent",  back_populates="classroom")
    students = relationship("Student", back_populates="classroom")
    subjects = relationship("Subject", back_populates="classroom")


class Parent(Base):
    """Registered parent who manages a classroom."""
    __tablename__ = "parents"

    id                  = Column(Integer, primary_key=True, index=True)
    first_name          = Column(String, nullable=False)
    last_name           = Column(String, nullable=False)
    # WhatsApp JID used for routing — may be @c.us or @lid format
    whatsapp_jid        = Column(String, unique=True, nullable=False, index=True)
    classroom_id        = Column(Integer, ForeignKey("classrooms.id"), nullable=True)
    # Credentials stored encrypted — never plaintext
    encrypted_username  = Column(Text, nullable=True)
    encrypted_password  = Column(Text, nullable=True)
    student_ids         = Column(JSON, nullable=True)   # e.g. [2036, 7505]
    is_active           = Column(Boolean, default=True)
    registered_at       = Column(DateTime, nullable=True)
    created_at          = Column(DateTime, default=datetime.utcnow)

    classroom = relationship("Classroom", back_populates="parents")
    students  = relationship("Student", back_populates="parent")


class InviteCode(Base):
    """One-time codes generated by admin to let parents register."""
    __tablename__ = "invite_codes"

    id          = Column(Integer, primary_key=True, index=True)
    code        = Column(String, unique=True, nullable=False, index=True)
    # Optional label so admin remembers who this code is for (e.g. "Maria Garcia")
    label       = Column(String, nullable=True)
    # active → used (after successful registration) | revoked (manually cancelled)
    status      = Column(String, default="active", nullable=False)
    created_at  = Column(DateTime, default=datetime.utcnow)
    used_at     = Column(DateTime, nullable=True)
    parent_id   = Column(Integer, ForeignKey("parents.id"), nullable=True)


class RegistrationSession(Base):
    """Tracks in-progress parent onboarding conversations."""
    __tablename__ = "registration_sessions"

    id          = Column(Integer, primary_key=True, index=True)
    # chat_jid is the sender's WhatsApp JID (e.g. "267469222600842@lid").
    # Used as the primary lookup key — we know this from the very first message.
    chat_jid    = Column(String, unique=True, nullable=False, index=True)
    state       = Column(String, nullable=False)   # see registration.py STATES
    data        = Column(JSON, default=dict)        # temp data during flow
    updated_at  = Column(DateTime, default=datetime.utcnow)


class Student(Base):
    __tablename__ = "students"

    id           = Column(Integer, primary_key=True)
    name         = Column(String, nullable=False)
    grade        = Column(String, nullable=False)
    classroom_id = Column(Integer, ForeignKey("classrooms.id"), nullable=True)
    parent_id    = Column(Integer, ForeignKey("parents.id"), nullable=True)

    classroom    = relationship("Classroom", back_populates="students")
    parent       = relationship("Parent", back_populates="students")
    assignments  = relationship("Assignment", back_populates="student")


class Subject(Base):
    __tablename__ = "subjects"

    id           = Column(Integer, primary_key=True, autoincrement=True)
    materia_id   = Column(Integer, nullable=False, index=True)
    name         = Column(String, nullable=False)
    icon         = Column(String, nullable=True)
    classroom_id = Column(Integer, ForeignKey("classrooms.id"), nullable=True)

    classroom    = relationship("Classroom", back_populates="subjects")


class Assignment(Base):
    __tablename__ = "assignments"

    id           = Column(Integer, primary_key=True)   # asigId from Seduca
    student_id   = Column(Integer, ForeignKey("students.id"), nullable=False, index=True)
    title        = Column(Text)
    type         = Column(String)
    date         = Column(String, index=True)          # YYYY-MM-DD
    created_at   = Column(String)
    subject_id   = Column(Integer, index=True)
    description  = Column(Text)
    materials    = Column(Text)
    summary      = Column(Text)
    updated_at   = Column(String)
    short_url    = Column(String)

    student = relationship("Student", back_populates="assignments")
